# frozen_string_literal: true

require 'rubygems'
require 'rubygems/package_task'
require 'rdoc/task'
require 'find'

# Don't include resource forks in tarballs on Mac OS X.
ENV['COPY_EXTENDED_ATTRIBUTES_DISABLE'] = 'true'
ENV['COPYFILE_DISABLE'] = 'true'

# Gemspec
gemspec = Gem::Specification.new do |s|
  s.name = 'riemann-rabbitmq'
  s.version = '0.1.5'
  s.author = 'Gavin Sandie'
  s.email = 'beach@vicecity.co.uk'
  s.homepage = 'https://github.com/riemann/riemann-tools'
  s.platform = Gem::Platform::RUBY
  s.summary = 'Submits RabbitMQ stats to riemann.'
  s.license = 'MIT'

  s.add_runtime_dependency 'riemann-tools', '~> 1.0', '>= 1.1.1'
  s.add_runtime_dependency 'faraday', '~> 2.3', '>= 2.3.0'
  s.add_runtime_dependency 'json', '~> 2.6', '>=2.6.2'

  s.files = FileList['bin/*', 'LICENSE', 'README.md'].to_a
  s.executables |= Dir.entries('bin/')

  s.required_ruby_version = Gem::Requirement.new('>= 2.6.0')
end

Gem::PackageTask.new gemspec do |p|
end
